/// <reference types="next" />
/// <reference types="next/image-types/global" />

// Normally auto-generated by Next.js (next dev/build) and gitignored, but this
// repo's CI runs `tsc --noEmit` before any next command would create it on a
// fresh checkout - so it's committed here instead. Deliberately omits the
// "./.next/types/routes.d.ts" reference next build normally adds: that path
// only exists after a build, and referencing a file that doesn't exist yet
// would fail tsc outright. `next build` will still rewrite this file locally
// (which is fine - the routes reference only matters once .next/ exists).
