<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>
		4.0.0
	</modelVersion>
	<parent>
		<groupId>
			org.springframework.boot
		</groupId>
		<artifactId>
			spring-boot-starter-parent
		</artifactId>
		<version>
			3.3.5
		</version>
		<relativePath />
		<!-- lookup parent from repository -->
	</parent>
	<groupId>
		com.backend
	</groupId>
	<artifactId>
		hotel
	</artifactId>
	<version>
		0.0.1-SNAPSHOT
	</version>
	<name>
		hotel
	</name>
	<description>
		Demo project for Spring Boot
	</description>
	<properties>
		<java.version>
			21
		</java.version>
	</properties>
	<dependencies>
		<!-- Spring Boot Starter for Data MongoDB Reactive -->
		 <!-- Spring Boot Starter for Reactive MongoDB -->
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-mongodb-reactive</artifactId>
    </dependency>
		<!-- Spring Boot Starter for GraphQL -->
		<dependency>
			<groupId>
				org.springframework.boot
			</groupId>
			<artifactId>
				spring-boot-starter-graphql
			</artifactId>
		</dependency>
		<!-- Spring Boot Starter for WebFlux -->
		<dependency>
			<groupId>
				org.springframework.boot
			</groupId>
			<artifactId>
				spring-boot-starter-webflux
			</artifactId>
		</dependency>
		<!-- Lombok for reducing boilerplate code -->
		<dependency>
			<groupId>
				org.projectlombok
			</groupId>
			<artifactId>
				lombok
			</artifactId>
			<optional>
				true
			</optional>
		</dependency>
		<!-- Spring Boot Starter Test for testing -->
		<dependency>
			<groupId>
				org.springframework.boot
			</groupId>
			<artifactId>
				spring-boot-starter-test
			</artifactId>
			<scope>
				test
			</scope>
		</dependency>
		<dependency>
			<groupId>
				org.springframework.boot
			</groupId>
			<artifactId>
				spring-boot-starter-graphql
			</artifactId>
		</dependency>

		
		<!-- Reactor Test for testing reactive code -->
		<dependency>
			<groupId>
				io.projectreactor
			</groupId>
			<artifactId>
				reactor-test
			</artifactId>
			<scope>
				test
			</scope>
		</dependency>
		<!-- Spring GraphQL Test Dependency -->
		<dependency>
			<groupId>
				org.springframework.graphql
			</groupId>
			<artifactId>
				spring-graphql-test
			</artifactId>
			<scope>
				test
			</scope>
		</dependency>
		<!--
		Why All Three Are Needed
		You need all three dependencies because:
		
		jjwt-api: Defines the API you work with.
		jjwt-impl: Provides the functionality behind the API.
		jjwt-jackson: Handles JSON serialization/deserialization for custom claims in JWT.
		-->
		<!--
		This is the main library thart provide me Define JWT structures (Header, Claims, Signature).
		Create JWTs using builders (JwtBuilder).
		Parse JWTs using the JwtParser interface) ONLY PROVIDE THE INTERFACES
		-->
		<dependency>
			<groupId>
				io.jsonwebtoken
			</groupId>
			<artifactId>
				jjwt-api
			</artifactId>
			<version>
				0.11.5
			</version>
		</dependency>
		<!-- THIS PROVIDE THE LOGIC OF ALL INTERFACES ABOUT THIS LIBRARY -->
		<dependency>
			<groupId>
				io.jsonwebtoken
			</groupId>
			<artifactId>
				jjwt-impl
			</artifactId>
			<version>
				0.11.5
			</version>
		</dependency>
		<!-- HANDLE THE SERIALIZACION AND DESARALIZCION OF THE CLAIMS -->
		<dependency>
			<groupId>
				io.jsonwebtoken
			</groupId>
			<artifactId>
				jjwt-jackson
			</artifactId>
			<version>
				0.11.5
			</version>
		</dependency>
		<dependency>
			<groupId>
				org.springframework.boot
			</groupId>
			<artifactId>
				spring-boot-starter-security
			</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<!-- Maven Compiler Plugin for Lombok annotation processing -->
			<plugin>
				<groupId>
					org.apache.maven.plugins
				</groupId>
				<artifactId>
					maven-compiler-plugin
				</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>
								org.projectlombok
							</groupId>
							<artifactId>
								lombok
							</artifactId>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<!-- Spring Boot Maven Plugin for running Spring Boot applications -->
			<plugin>
				<groupId>
					org.springframework.boot
				</groupId>
				<artifactId>
					spring-boot-maven-plugin
				</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>
								org.projectlombok
							</groupId>
							<artifactId>
								lombok
							</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
